/**
 * access-config.js — generated by scripts/setup-access.js
 *
 * Contains an Anthropic API key encrypted under a password using PBKDF2 +
 * AES-256-GCM. Safe to commit: without the password, the ciphertext is not
 * decryptable. Each guess requires a full PBKDF2 derivation, which is slow
 * by design.
 *
 * Re-run scripts/setup-access.js to rotate the password or the API key.
 */
window.ACCESS_CONFIG = {
  "version": 1,
  "algorithm": "AES-256-GCM",
  "kdf": {
    "name": "PBKDF2",
    "hash": "sha256",
    "iterations": 250000
  },
  "salt": "nW2THDAUEWlcNUx78vPqrA==",
  "iv": "nsztg5GvVNJG2N4l",
  "cipher": "8qzM/01t/6rKFip5MbpZ9fVbwC3hJf1pSOvZc1F7ix1FW4v1Pw3xaPlII1KcdaHvpXu1lLAzVesDO6o3aGHqpgg//Bfi/fOmtJKy2IVgDKtV+/o907mdbkhdEFmTWqIuwQkUQfpzK5t0ExHz/vATfEnj7FJ7dXRXGCHNqg=="
};
